name: Output Info

on: workflow_dispatch

jobs:
  info:
    runs-on: ubuntu-latest
    steps:
      - name: Output Github Context
        run: |
          echo "Repository: ${{ github.repository }}"
          echo "Workflow: ${{ github.workflow }}"
          echo "Event Name: ${{ github.event_name }}"
          echo "Actor: ${{ github.actor }}"
          echo "Run ID: ${{ github.run_id }}"
          echo "Run Number: ${{ github.run_number }}"
          echo "Job Status: ${{ job.status }}"
          echo "Current Time: $(date)"
          echo "Branch: ${{ github.ref }}"
          echo "Commit SHA: ${{ github.sha }}"
          echo "Event Payload: ${{ toJson(github.event) }}"
          echo "Workflow Run URL: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
          echo "Workflow Run HTML URL: ${{ github.event.workflow_run.html_url }}"
          echo "Workflow Run ID: ${{ github.event.workflow_run.id }}"
          echo "Workflow Run Name: ${{ github.event.workflow_run.name }}"
          echo "Workflow Run Status: ${{ github.event.workflow_run.status }}"
          echo "Workflow Run Conclusion: ${{ github.event.workflow_run.conclusion }}"
          echo "Workflow Run Created At: ${{ github.event.workflow_run.created_at }}"
          echo "Workflow Run Updated At: ${{ github.event.workflow_run.updated_at }}"
          echo "Workflow Run Triggered By: ${{ github.event.workflow_run.triggered_by }}"
         